### ISSUE TITLE
Run January MONDO impact report

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/mondo-notifier#2]
Since the automated planned obsoletion and name change notifications is not ready, we are committed to running a report against GG to provide Erin R. with some advanced notifications.

This is time sensitive, so it's urgency takes priority.

**Comment by larrybabb** [comment]
Produced the report for the Dec 30 release of Mondo and sent it to Erin, Danielle et al. 

Here's a copy of the email that was sent


>There are now 6 MONDO terms in GeneGraph that have curations and are on the Planned >Obsoletion list as of Dec 30st:
>1. mucopolysaccharidosis type 2
>MONDO:0010674
>MONDO GitHub Issue 3787
>Planned Date for Obsoletion: 1/1/22
>Impact: Actionability, Gene Dosage, Gene Validity
>
>2. methylmalonic acidemia without homocystinuria
>MONDO:0017390
>MONDO GitHub Issue 3886
>Planned Date for Obsoletion: 3/1/22
>Impact: Gene Validity
>
>3. chondrodysplasia punctata 2, X-linked dominant
>MONDO:0026782
>MONDO GitHub Issue 3906
>Planned Date for Obsoletion: 2/1/22
>Impact: Gene Dosage
>
>4. benign familial neonatal-infantile seizures
>MONDO:0011140
>MONDO GitHub Issue 4073
>Planned Date for Obsoletion: 3/1/22
>Impact: Gene Validity
>
>5. class I glucose-6-phosphate dehydrogenase deficiency
>MONDO:0018750
>MONDO GitHub Issue 4202
>Planned Date for Obsoletion: 3/1/22
>Impact: Actionability
>
>6. hyperinsulinism due to short chain 3-hydroxylacyl-CoA dehydrogenase deficiency
>MONDO:0009278
>MONDO GitHub Issue 3977
>Planned Date for Obsoletion: 2/1/22
>Impact: Gene Validity
>
>Below are terms in MONDO that have changes to the label that impact at least one >published curation in GeneGraph on the website as of Dec 30th.
>
>C1.    Mass update of the term "deafness" to "hearing loss" in all disease names.
>51 Disease Names were impacted by this mass update across all 3 workstreams. >Essentially any time the term "deafness" appeared in a disease name they mass updated it >to "hearing loss".  (if you'd like a specific list of the diseases please let me know)
>
>C2.     MONDO:0020682 - Ehlers-Danlos syndrome, progeroid type 1
>Impact: Gene Dosage
>Change : Label
>Old Value :  Ehlers-Danlos syndrome, progeroid type 1
>New Value : Ehlers-Danlos syndrome, spondylodysplastic type, 1
>
>C3.     MONDO:0014353 - PGM3-CDG
>Impact: Gene Dosage
>Change : Label
>Old Value :  PGM3-CDG
>New Value :immunodeficiency 23
>
>C4.     MONDO:0018466 - hereditary late onset Parkinson disease
>Impact:  Actionability
>Change : Label
>Old Value : hereditary late onset Parkinson disease
>New Value : obsolete hereditary late onset Parkinson disease
