### ISSUE TITLE
Dosage data/website display of MONDO diseases notifications

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/mondo-notifier#3]
It's unclear if this needs to impact the Dosage Jira instance or not. My assumption is that we intend to have the dosage data be exposed to the public primarily through GeneGraph and the Website. If that is the case then the GG transformational service that standardizes the data being pulled from the Dosage Jira instance to the GG website backing datastore should consume and flag all disease name changes while preserving the original name saved by the Jira system during approval and/or publication.  In addition, there is an expectation that any dosage MONDO diseases impacted by forthcoming obsoletions should be collected and sent to the Dosage Stakeholder Group Email list so they can be notified of any current or past dosage curations that will be impacted by obsoletions. I suspect notifying of name changes that are actually occurring should be pushed with notifications as well. 

Ticket on SP Board: [https://broadinstitute.atlassian.net/jira/software/c/projects/CSP/boards/667?modal=detail&selectedIssue=CSP-210&search=mondo](url)

**Comment by larrybabb** [comment]
currently @larrybabb runs a monthly report when MONDO releases a new dataset which cross references any mondo terms in genegraph that have a published ACI, DCI or GCI classification. This report is manually assembled in a couple steps (not documented!) by Larry and emailed to Erin Riggs and a cast of others from the GCI and ACI teams.

This is not a sustainable process and should be automated. 

The original plan was to have the genegraph system consume the mondo release notifications and raise alerts in a manner that was easily accessible and identifiable by the users.

We will keep this in the backlog until the cost outweighs the benefits of doing this manually.

**Comment by larrybabb** [comment]
Closing this since the stakeholders have not prioritized this for this for Dosage. The current manually run report suffices.
